### ISSUE TITLE
'Prev' bug

### ISSUE THREAD

**Issue by DaVinci789** [disorientedperson/python-adventure-game#19]
The 'prev' command allows one to re-enter a room otherwise not allowed.

To Reproduce:
- Start game with no save file
- Exit room (mirror, xyzzy)
- You should be in home
- Type 'prev'
- You'll end up back in the first room.

**Comment by disorientedperson** [comment]
Maybe another location parameter (like `invisible=False`)?

**Comment by DaVinci789** [comment]
I tried that with the last commit, but it still allows it to pass through
+
